method-whitelist:
- getPlayerLimit
- dynmap.getPort
logins:
    usernameGoesHere: passwordGoesHere
options:
    startup-delay: 2000
    port: 20059
    ip-whitelist: []
    log-to-console: true
    log-to-file: 'false'
    salt: 'salt goes here'
    anyone-can-use-calladmin: true
    use-new-api: false
    stream_pusher:
        max_queue_age: 30
        max_queue_length: 500
