name: JSONAPI
main: com.alecgorge.minecraft.jsonapi.JSONAPI
version: 5.7.0
description: Control your server and fetch information from your server.
website: http://mcjsonapi.com/
author: Alec Gorge
depend: [Vault, ProtocolLib]
softdepend: [RemoteToolkitPlugin, dynmap]
commands:
  reloadjsonapi:
    description: Reloads the API methods for JSONAPI.
    usage: /<command>
  jsonapi-list:
    description: Lists all the methods and namespaces currently loaded for JSONAPI
    usage: /<command>
  calladmin:
    description: Sends a message to the admin of the server if they have Adminium installed on their iOS device.
    usage: /<command> <why>
  jsonapi:
    usage: '/<command> [status|list|reload|reloadgroups|subscribe <source name> <url>|users [list|<username> password|add <username> <password>]]'
    description: '/jsonapi [status|list|reload|reloadgroups|subscribe <source name> <url>|users [list|<username> password|add <username> <password>]]'
permissions:
  jsonapi.command:
    description: The ability to use the /jsonapi and /adminium commands
    default: op
  jsonapi.calladmin:
    description: 'NOTE If you want to use this, make sure you set `anyone-can-use-calladmin` to false in config.yml. Allows users to send a push notification to the devices connected with Adminium.'
    default: op
