#!/usr/bin/env bash
# Generated with the command ./jsonapi build all

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo "Removing old builds"
rm -rf builds/*

echo "Building 1.10.2-R0.1-SNAPSHOT"
mvn clean install $@ -DmcPackage=v1_10_R1 -DspigotVersion=1.10.2-R0.1-SNAPSHOT

rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi

echo "Building 1.11.2-R0.1-SNAPSHOT"
mvn clean install $@ -DmcPackage=v1_11_R1 -DspigotVersion=1.11.2-R0.1-SNAPSHOT

rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi

echo "Building 1.11.2-R0.1-SNAPSHOT"
mvn clean install $@ -DmcPackage=v1_11_R1 -DspigotVersion=1.11.2-R0.1-SNAPSHOT

rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi
