#!/usr/bin/env bash
# Generated with the command ./jsonapi build all

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo "Removing old builds"
rm -rf builds/*


echo "Building 1.9.2-R0.1-SNAPSHOT"
mvn clean install $@ -DmcPackage=v1_9_R1 -DspigotVersion=1.9.2-R0.1-SNAPSHOT

rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi

echo "Building 1.9.4-R0.1-SNAPSHOT"
mvn clean install $@ -DmcPackage=v1_9_R2 -DspigotVersion=1.9.4-R0.1-SNAPSHOT

rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi

echo "Building 1.10.2-R0.1-SNAPSHOT"
mvn clean install $@ -DmcPackage=v1_10_R1 -DspigotVersion=1.10.2-R0.1-SNAPSHOT

rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi
