#!/usr/bin/env bash
# Generated with the command ./jsonapi eclipse 1.12

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
mvn eclipse:eclipse $@ -DmcPackage=v1_12_R1 -DspigotVersion=1.12-R0.1-SNAPSHOT -Dmc1120rNewer=yes
