#!/usr/bin/env bash
# Generated with the command ./jsonapi test 1.4.7

jarVersion=${1:-BLEEDING}
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
mvn clean install $@ -Dversion=$jarVersion -DmcPackage=v1_4_R1 -DcbVersion=1.4.7-R1.0 -Dmc16OrNewer=no -Dmc17OrNewer=no && cd test/ && java -Xmx256M -jar craftbukkit-1.4.7-R1.0.jar
cd $DIR
