#!/usr/bin/env bash
# Generated with the command ./jsonapi test 1.7.9

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
mvn clean install $@ -DmcPackage=v1_7_R3 -DcbVersion=1.7.9-R0.2-SNAPSHOT -Dmc16OrNewer=yes -Dmc17OrNewer=yes && cd test/ && java -Xmx256M -jar craftbukkit-1.7.9-R0.2-SNAPSHOT.jar
cd $DIR
