#!/usr/bin/env bash
# Generated with the command ./jsonapi test 1.8.8

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
mvn clean install $@ -DmcPackage=v1_8_R3 -DspigotVersion=1.8.8-R0.1-SNAPSHOT && cd test/ && java -Xmx2G -jar spigot-1.8-R0.1-SNAPSHOT.jar
cd $DIR
