#!/usr/bin/env bash
# Generated with the command ./jsonapi test 1.6.4

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
mvn clean install $@ -DmcPackage=v1_6_R3 -DcbVersion=1.6.4-R2.0 -Dmc16OrNewer=yes -Dmc17OrNewer=no && cd test/ && java -Xmx256M -jar craftbukkit-1.6.4-R2.0.jar
cd $DIR
